# Generated by Django 4.0.6 on 2022-07-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='assigned_roles',
            field=models.ManyToManyField(blank=True, to='village.role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village.faction'),
        ),
    ]
