# Generated by Django 4.0.6 on 2022-07-28 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('village', '0002_alter_membership_assigned_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='occupants',
        ),
        migrations.AddField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='Alive'),
        ),
        migrations.AddField(
            model_name='player',
            name='assigned_roles',
            field=models.ManyToManyField(blank=True, to='village.role'),
        ),
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village.faction'),
        ),
        migrations.AddField(
            model_name='player',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village.village'),
        ),
        migrations.AddField(
            model_name='village',
            name='overseer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='village',
            name='status',
            field=models.TextField(default='About to begin.', verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
