# Generated by Django 4.0.6 on 2022-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_remove_village_occupants_player_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
