# Generated by Django 4.0.6 on 2022-07-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('descr', models.TextField(default='Description', verbose_name='Description')),
                ('obj', models.TextField(default='Objective', verbose_name='Objective')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True, verbose_name='Alive')),
                ('overseer', models.BooleanField(default=False, verbose_name='Overseer')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('prologue', models.TextField(default='Prologue', verbose_name='Prologue')),
                ('descr', models.TextField(default='Description', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.TextField(default="Hasn't started.", verbose_name='Status')),
                ('date_created', models.DateField()),
                ('occupants', models.ManyToManyField(through='salem.Membership', to='salem.player')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('descr', models.TextField(default='Description', verbose_name='Description')),
                ('notes', models.TextField(default='None', verbose_name='Notes')),
                ('tips', models.TextField(default='None', verbose_name='Tips')),
                ('tier', models.IntegerField(default=1, verbose_name='Tier')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.faction')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='assigned_roles',
            field=models.ManyToManyField(to='salem.role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.faction'),
        ),
        migrations.AddField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.player'),
        ),
        migrations.AddField(
            model_name='membership',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.village'),
        ),
        migrations.AddField(
            model_name='faction',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salem.theme'),
        ),
    ]
