# Generated by Django 4.0.6 on 2022-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
