# Generated by Django 4.0.5 on 2022-07-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setupper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assigned_role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='limits',
        ),
        migrations.RemoveField(
            model_name='role',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='role',
            name='xtras',
        ),
        migrations.AddField(
            model_name='player',
            name='assigned_roles',
            field=models.ManyToManyField(to='setupper.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='notes',
            field=models.TextField(default='None', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='role',
            name='tier',
            field=models.IntegerField(default=1, verbose_name='Tier'),
        ),
        migrations.AddField(
            model_name='role',
            name='tips',
            field=models.TextField(default='None', verbose_name='Tips'),
        ),
        migrations.AlterField(
            model_name='role',
            name='faction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='setupper.faction'),
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
