# Generated by Django 4.0.5 on 2022-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupper', '0002_remove_player_assigned_role_remove_role_limits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
