# Generated by Django 4.0.5 on 2022-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupper', '0004_alter_player_assigned_roles_alter_role_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assigned_roles',
            field=models.ManyToManyField(blank=True, to='setupper.role'),
        ),
    ]
