# Generated by Django 4.0.6 on 2022-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupper', '0005_alter_player_assigned_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('alive', models.BooleanField(default=True, verbose_name='Alive')),
                ('assigned_roles', models.ManyToManyField(blank=True, to='setupper.role')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
